# Generated by Django 5.0.5 on 2024-05-16 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.TextField(max_length=35, unique=True)),
                ('current_price', models.IntegerField()),
                ('target_price', models.IntegerField()),
                ('is_open', models.BooleanField(default=True)),
                ('open_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
