# Generated by Django 5.0.5 on 2024-05-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_alerts_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='asset',
            field=models.TextField(max_length=35),
        ),
    ]
