# Generated by Django 5.0.5 on 2024-05-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alter_alerts_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
